### ISSUE TITLE
ignitech.cpp return value of ignition.advance_2_deg;

### ISSUE THREAD

**Issue by kurt-k3po** [techie66/libIgnitech#13]
ignitech.cpp

I think
get_advance(2) , get_advance(3), get_advance(4) in sipmle getter section always return ignition.advance_1_deg.

return has to be ignition.advance_2_deg; ignition.advance_3_deg; ignition.advance_4_deg; acordingly

https://github.com/techie66/libIgnitech/blob/6bafceefb269a18af7a1dbc1788fdf047c937971/src/ignitech.cpp#L514-L539

**Comment by techie66** [comment]
Absolutely right. If you can make a pull request, I'll merge it. Or if not, I can get to it in a day or so.

**Comment by kurt-k3po** [comment]
Sorry, can't make a pull request.
